"""Tests for ``lagrangian.operator_action.gauge_variation``.

These tests exercise the **infinitesimal** gauge variation operator on
already-lowered ``CompiledLagrangian`` objects:

* matter pieces (scalars and fermions) under U(1) and a small non-abelian
  group built by hand,
* the gauge-boson variation (homogeneous + inhomogeneous parts),
* pure Yang-Mills ``-1/4 F^2``,
* explicit "wrong charge / wrong representation" checks.

We verify gauge invariance by exporting ``apply_operator(delta).to_symbolica()``
and running it through the project's tensor-canonicaliser (which knows how
to relabel dummy spinor / Lorentz / adjoint indices and contract the
Minkowski metric). The exact dummy labels generated by lowering and by
``gauge_variation`` are passed in explicitly so the check is deterministic.
"""

from __future__ import annotations

import pytest

from symbolica import Expression, S

from model import (
    CovD,
    Field,
    FieldStrength,
    Gamma,
    GaugeGroup,
    GaugeRepresentation,
    LORENTZ_INDEX,
    Model,
    PartialD,
    WEAK_ADJ_INDEX,
    WEAK_FUND_INDEX,
    dirac_field,
    scalar_field,
)
from model.metadata import COLOR_ADJ_INDEX, COLOR_FUND_INDEX
from model.interactions import InteractionTerm
from lagrangian.operator_action import (
    FieldOperator,
    apply_field_operator_to_term,
    gauge_variation,
)
from symbolic.spenso_structures import (
    gauge_generator,
    structure_constant,
    weak_gauge_generator,
    weak_structure_constant,
)
from symbolic.tensor_canonicalization import canonize_full


def _zero(
    expr,
    *,
    lorentz=(),
    adjoint=(),
    color_fund=(),
    spinor=(),
    weak_fund=(),
    weak_adj=(),
    field_heads=(),
):
    """Canonicalise ``expr`` with the given dummy index symbols and return
    ``True`` iff the result is the symbolic zero.
    """
    canonical = canonize_full(
        expr,
        lorentz_indices=tuple(lorentz),
        adjoint_indices=tuple(adjoint),
        color_fund_indices=tuple(color_fund),
        spinor_indices=tuple(spinor),
        weak_fund_indices=tuple(weak_fund),
        weak_adj_indices=tuple(weak_adj),
        field_heads=tuple(field_heads),
    )
    return canonical.to_canonical_string() == "0"


# ---------------------------------------------------------------------------
# 1) API basics
# ---------------------------------------------------------------------------


def test_gauge_variation_returns_field_operator():
    """``gauge_variation`` returns a ``FieldOperator`` whose parity is even."""

    g = S("g")
    A = Field("A", spin=1, indices=(LORENTZ_INDEX,), self_conjugate=True)
    U1 = GaugeGroup(name="U1", abelian=True, coupling=g, charge="Q", gauge_boson=A)

    delta = gauge_variation(group=U1, parameter="alpha")
    assert isinstance(delta, FieldOperator)
    assert delta.parity == 0
    assert hasattr(delta, "_gauge_parameter_field")
    assert delta._gauge_parameter_field.name == "alpha"


def test_non_abelian_group_without_gauge_boson_raises():
    """Non-abelian gauge variation needs a gauge boson to read the adjoint
    index off; building it without one is a clear error.
    """

    g = S("g3")
    SU3 = GaugeGroup(
        name="SU3",
        abelian=False,
        coupling=g,
        gauge_boson=None,
        structure_constant=structure_constant,
        representations=(
            GaugeRepresentation(
                index=COLOR_FUND_INDEX,
                generator_builder=gauge_generator,
                name="fundamental",
            ),
        ),
    )
    with pytest.raises(ValueError, match="no gauge_boson"):
        gauge_variation(group=SU3, parameter="alpha")


# ---------------------------------------------------------------------------
# 2) U(1) matter sector
# ---------------------------------------------------------------------------


def _u1_setup():
    g = S("g")
    A = Field("A", spin=1, indices=(LORENTZ_INDEX,), self_conjugate=True)
    U1 = GaugeGroup(name="U1", abelian=True, coupling=g, charge="Q", gauge_boson=A)
    return g, A, U1


def test_u1_mass_term_is_gauge_invariant():
    """``m^2 Phibar Phi`` for a charged complex scalar is gauge-invariant
    independently of any derivatives or gauge field, so ``delta L = 0``
    exactly (no metric simplification needed).
    """

    g, A, U1 = _u1_setup()
    m2 = S("m2")
    phi = scalar_field("Phi", self_conjugate=False, quantum_numbers={"Q": 1})
    L = Model(
        gauge_groups=(U1,),
        fields=(phi, A),
        lagrangian_decl=m2 * phi.bar * phi,
    ).lagrangian()

    delta = gauge_variation(group=U1, parameter="alpha")
    dL = L.apply_operator(delta)
    assert dL.to_symbolica().expand().to_canonical_string() == "0"


def test_u1_mass_term_wrong_charge_is_not_gauge_invariant():
    """A *real* (self-conjugate) scalar cannot carry a U(1) charge: if we
    pretend otherwise, ``delta L`` is non-zero. This is the minimal "wrong
    charge gives nonzero variation" check.
    """

    g, A, U1 = _u1_setup()
    phi = scalar_field("Phi", self_conjugate=True, quantum_numbers={"Q": 1})
    L = Model(
        gauge_groups=(U1,),
        fields=(phi, A),
        lagrangian_decl=S("m2") * phi.bar * phi,
    ).lagrangian()

    delta = gauge_variation(group=U1, parameter="alpha")
    dL = L.apply_operator(delta)
    canonical = dL.to_symbolica().expand().to_canonical_string()
    assert canonical != "0"


def test_u1_scalar_kinetic_term_is_gauge_invariant():
    """``(D_mu Phi)^dagger (D^mu Phi)`` for a charged complex scalar.

    The lowered kinetic term has four pieces (kinetic, two trilinears with
    one ``A``, one quartic with two A's and a metric). The variation
    cancels only after Minkowski-metric contraction; ``canonize_full``
    takes care of that.
    """

    g, A, U1 = _u1_setup()
    mu = S("mu")
    phi = scalar_field("Phi", self_conjugate=False, quantum_numbers={"Q": 1})

    L = Model(
        gauge_groups=(U1,),
        fields=(phi, A),
        lagrangian_decl=CovD(phi.bar, mu) * CovD(phi, mu),
    ).lagrangian()

    delta = gauge_variation(group=U1, parameter="alpha")
    dL = L.apply_operator(delta)

    # The CovD lowering introduces an explicit Minkowski metric on the
    # ``A A`` quartic piece, so contract that first against the relevant
    # tensor heads. Lorentz dummies are ``mu`` (the bare kinetic label)
    # and ``nu`` (the metric's second slot).
    assert _zero(
        dL.to_symbolica(),
        lorentz=(mu, S("nu")),
        field_heads=(A,),
    )


def test_u1_fermion_kinetic_term_is_gauge_invariant():
    """QED kinetic ``i psibar gamma(mu) D_mu psi`` is gauge invariant.

    The two relevant dummy spinor labels are the ones emitted by the CovD
    lowering: ``i_bar_psi_U1`` / ``i_psi_U1`` for the gauge piece and
    ``i_bar_psi_covd`` / ``i_psi_covd`` for the bare-derivative piece.
    """

    g, A, U1 = _u1_setup()
    mu = S("mu")
    psi = dirac_field("psi", quantum_numbers={"Q": -1})

    L = Model(
        gauge_groups=(U1,),
        fields=(psi, A),
        lagrangian_decl=Expression.I * psi.bar() * Gamma(mu) * CovD(psi, mu),
    ).lagrangian()

    delta = gauge_variation(group=U1, parameter="alpha")
    dL = L.apply_operator(delta)
    assert _zero(
        dL.to_symbolica(),
        lorentz=(mu,),
        spinor=(
            S("i_bar_psi_U1"),
            S("i_psi_U1"),
            S("i_bar_psi_covd"),
            S("i_psi_covd"),
        ),
    )


def test_u1_yukawa_with_balanced_charges_is_gauge_invariant():
    """Yukawa ``y * Phi * eta.bar * eta`` is invariant iff the charges
    satisfy ``q_Phi + q_eta - q_eta = q_Phi = 0`` (since both ``eta`` slots
    appear, one with .bar). Here we take all three with zero charge - the
    minimal non-trivial Dirac+scalar coupling - and check explicitly.

    The non-trivial "balanced charges" case is captured by mass-type
    cancellations; this complement test guards against accidental sign
    bugs on the scalar slot when the charge is zero.
    """

    g, A, U1 = _u1_setup()
    phi = scalar_field("Phi", self_conjugate=False, quantum_numbers={"Q": 0})
    psi = dirac_field("psi", quantum_numbers={"Q": 0})

    L = Model(
        gauge_groups=(U1,),
        fields=(phi, psi, A),
        lagrangian_decl=S("y") * psi.bar() * psi() * phi,
    ).lagrangian()

    delta = gauge_variation(group=U1, parameter="alpha")
    dL = L.apply_operator(delta)
    assert dL.to_symbolica().expand().to_canonical_string() == "0"


def test_u1_yukawa_with_unbalanced_charges_is_not_invariant():
    """Pure ``y Phi psibar psi`` with ``q_Phi != 0`` (and equal q for
    ``psi`` and ``psibar``) does not satisfy charge conservation, so the
    variation is nonzero. This is the explicit "wrong-charge" check.
    """

    g, A, U1 = _u1_setup()
    phi = scalar_field("Phi", self_conjugate=False, quantum_numbers={"Q": 1})
    psi = dirac_field("psi", quantum_numbers={"Q": 0})

    L = Model(
        gauge_groups=(U1,),
        fields=(phi, psi, A),
        lagrangian_decl=S("y") * psi.bar() * psi() * phi,
    ).lagrangian()

    delta = gauge_variation(group=U1, parameter="alpha")
    dL = L.apply_operator(delta)
    canonical = canonize_full(dL.to_symbolica()).to_canonical_string()
    assert canonical != "0"


# ---------------------------------------------------------------------------
# 3) Non-abelian matter (SU(3) fundamental scalar)
# ---------------------------------------------------------------------------


def _su3_setup():
    g = S("gS")
    # Gauge boson with one Lorentz slot and one adjoint slot.
    Ag = Field(
        "G",
        spin=1,
        indices=(LORENTZ_INDEX, COLOR_ADJ_INDEX),
        self_conjugate=True,
    )
    SU3 = GaugeGroup(
        name="SU3",
        abelian=False,
        coupling=g,
        gauge_boson=Ag,
        structure_constant=structure_constant,
        representations=(
            GaugeRepresentation(
                index=COLOR_FUND_INDEX,
                generator_builder=gauge_generator,
                name="fundamental",
            ),
        ),
    )
    return g, Ag, SU3


def _su3_pure_yang_mills_indices():
    lorentz = tuple(
        S(name)
        for name in (
            "mu",
            "nu",
            "mu_G_SU3_1",
            "mu_G_SU3_2",
            "mu_G_SU3_3",
            "mu_G_SU3_4",
            "rho_G_SU3",
            "rho_left_G_SU3",
            "rho_right_G_SU3",
            "rho_G_SU3_cubic",
        )
    )
    adjoint = (
        S("a_G_color_adj_id"),
        S("a_bar_G_color_adj_id"),
        *(S(f"a_delta_SU3_{slot}") for slot in range(1, 23)),
        *(S(f"color_adj_G_SU3_{slot}") for slot in range(1, 5)),
        S("a_mid_G_SU3"),
    )
    return lorentz, adjoint


def _su3_sum_setup():
    g = S("gS")
    Ag = Field(
        "G",
        spin=1,
        indices=(LORENTZ_INDEX, COLOR_ADJ_INDEX),
        self_conjugate=True,
    )
    SU3 = GaugeGroup(
        name="SU3sum",
        abelian=False,
        coupling=g,
        gauge_boson=Ag,
        structure_constant=structure_constant,
        representations=(
            GaugeRepresentation(
                index=COLOR_FUND_INDEX,
                generator_builder=gauge_generator,
                name="fundamental_sum",
                slot_policy="sum",
            ),
        ),
    )
    return g, Ag, SU3


def _su2_setup():
    g = S("g2")
    Wg = Field(
        "W",
        spin=1,
        indices=(LORENTZ_INDEX, WEAK_ADJ_INDEX),
        self_conjugate=True,
    )
    SU2 = GaugeGroup(
        name="SU2L",
        abelian=False,
        coupling=g,
        gauge_boson=Wg,
        structure_constant=weak_structure_constant,
        representations=(
            GaugeRepresentation(
                index=WEAK_FUND_INDEX,
                generator_builder=weak_gauge_generator,
                name="doublet",
            ),
        ),
    )
    return g, Wg, SU2


def test_non_abelian_scalar_mass_term_is_gauge_invariant():
    """For a complex scalar in the fundamental of SU(3), the colour-singlet
    mass ``m^2 Phibar Phi`` (with a contracted colour index) is gauge
    invariant: the two T^a contributions cancel because they enter
    Phi and Phibar with opposite signs and matching index structure.
    """

    g, Ag, SU3 = _su3_setup()
    c = S("c")
    phi = scalar_field(
        "Phi",
        self_conjugate=False,
        indices=(COLOR_FUND_INDEX,),
    )

    L = Model(
        gauge_groups=(SU3,),
        fields=(phi, Ag),
        lagrangian_decl=S("m2") * phi.bar(c) * phi(c),
    ).lagrangian()

    delta = gauge_variation(group=SU3, parameter="alpha")
    dL = L.apply_operator(delta)
    assert _zero(
        dL.to_symbolica(),
        color_fund=(c, S("c_delta_SU3_1"), S("c_delta_SU3_3")),
        adjoint=(S("a_delta_SU3_2"), S("a_delta_SU3_4")),
    )


def test_non_abelian_singlet_coupled_to_fundamental_pair_is_gauge_invariant():
    """A singlet ``S`` multiplied by a contracted colour pair
    ``Phi.bar(c) Phi(c)`` is still a colour singlet, so the variation must
    vanish: the operator only rotates ``Phi`` and ``Phi.bar``, and their
    contributions cancel exactly like in the bare mass term.

    This guards against the operator accidentally rotating the singlet
    or breaking the cancellation between the two fundamental factors.
    """

    g, Ag, SU3 = _su3_setup()
    phi = scalar_field(
        "Phi", self_conjugate=False, indices=(COLOR_FUND_INDEX,),
    )
    sing = scalar_field("S", self_conjugate=True)
    c = S("c")

    L = Model(
        gauge_groups=(SU3,),
        fields=(phi, sing, Ag),
        lagrangian_decl=S("y") * sing * phi(c) * phi.bar(c),
    ).lagrangian()

    delta = gauge_variation(group=SU3, parameter="alpha")
    dL = L.apply_operator(delta)
    assert _zero(
        dL.to_symbolica(),
        color_fund=(c, S("c_delta_SU3_1"), S("c_delta_SU3_3")),
        adjoint=(S("a_delta_SU3_2"), S("a_delta_SU3_4")),
    )


def test_non_abelian_non_singlet_is_not_gauge_invariant():
    """A non-singlet construction with free colour indices does *not*
    cancel under an SU(3) variation. We build ``y Phi(c1) Phi.bar(c2)``
    with **uncontracted** ``c1`` and ``c2``; the two T^a contributions
    have different colour structures and do not sum to zero.
    """

    g, Ag, SU3 = _su3_setup()
    phi = scalar_field(
        "Phi", self_conjugate=False, indices=(COLOR_FUND_INDEX,),
    )
    c1, c2 = S("c1"), S("c2")

    L = Model(
        gauge_groups=(SU3,),
        fields=(phi, Ag),
        lagrangian_decl=S("y") * phi(c1) * phi.bar(c2),
    ).lagrangian()

    delta = gauge_variation(group=SU3, parameter="alpha")
    dL = L.apply_operator(delta)
    canonical = canonize_full(
        dL.to_symbolica(),
        color_fund_indices=(
            c1, c2,
            S("c_delta_SU3_1"), S("c_delta_SU3_3"),
        ),
        adjoint_indices=(S("a_delta_SU3_2"), S("a_delta_SU3_4")),
    ).to_canonical_string()
    assert canonical != "0", f"expected nonzero variation but got 0: {canonical}"


def test_non_abelian_slot_policy_sum_emits_one_variation_per_active_slot():
    """Repeated active representation slots contribute in first-seen slot order."""

    g, Ag, SU3 = _su3_sum_setup()
    phi = scalar_field(
        "PhiBi",
        self_conjugate=False,
        indices=(COLOR_FUND_INDEX, COLOR_FUND_INDEX),
    )
    c1, c2 = S("c1"), S("c2")

    L = Model(
        gauge_groups=(SU3,),
        fields=(phi, Ag),
        lagrangian_decl=phi(c1, c2),
    ).lagrangian()

    delta = gauge_variation(group=SU3, parameter="alpha")
    results = apply_field_operator_to_term(L.terms[0], delta)

    assert len(results) == 2
    first_labels = results[0].fields[1].field.unpack_slot_labels(results[0].fields[1].labels)
    second_labels = results[1].fields[1].field.unpack_slot_labels(results[1].fields[1].labels)

    assert first_labels[1] == c2
    assert first_labels[0] != c1
    assert second_labels[0] == c1
    assert second_labels[1] != c2

    first_coupling = str(results[0].coupling)
    second_coupling = str(results[1].coupling)
    assert "c1" in first_coupling
    assert "c2" in second_coupling
    assert "t(" in first_coupling.lower()
    assert "t(" in second_coupling.lower()


def test_non_abelian_slot_policy_sum_still_requires_explicit_labels():
    """Each active repeated slot must carry a concrete label."""

    g, Ag, SU3 = _su3_sum_setup()
    phi = scalar_field(
        "PhiBi",
        self_conjugate=False,
        indices=(COLOR_FUND_INDEX, COLOR_FUND_INDEX),
    )

    L = InteractionTerm(
        coupling=Expression.num(1),
        fields=(phi.occurrence(labels={COLOR_FUND_INDEX.kind: (S("c1"), None)}),),
    )
    delta = gauge_variation(group=SU3, parameter="alpha")
    with pytest.raises(ValueError, match="representation slot 2"):
        apply_field_operator_to_term(L, delta)


# ---------------------------------------------------------------------------
# 4) Non-abelian gauge sector
# ---------------------------------------------------------------------------


def test_non_abelian_gauge_boson_variation_has_inhomogeneous_and_structure_pieces():
    """The non-abelian gauge-boson variation splits as

        δ A^a_μ  =  + ∂_μ α^a  -  g f^{abc} α^b A^c_μ

    Verify, at the lowered-term level, that both summands are produced
    and that the inhomogeneous term carries a fresh ``∂_μ`` on α while
    the homogeneous term carries a structure constant ``f`` and an A
    factor.

    This is the structural building block used by the full pure-YM
    gauge-invariance argument. We assert structure rather than a full
    cancellation here because the YM cancellation between bilinear,
    cubic and quartic pieces of ``F^2`` is a global statement across
    many summands sharing lowered dummies, which is out of scope for
    the minimal first-cut tensor canonicaliser used here.
    """

    g, Ag, SU3 = _su3_setup()
    mu = S("mu")
    aa = S("aa")  # external adjoint label
    A_decl = Model(
        gauge_groups=(SU3,),
        fields=(Ag,),
        lagrangian_decl=Ag(mu, aa),
    ).lagrangian()
    assert len(A_decl.terms) == 1
    A_term = A_decl.terms[0]

    delta = gauge_variation(group=SU3, parameter="alpha")
    new_terms = apply_field_operator_to_term(A_term, delta)
    # Exactly two summands: inhomogeneous + homogeneous.
    assert len(new_terms) == 2

    # The first summand carries one fresh derivative ∂_μ on α(a).
    inhom, hom = new_terms
    assert len(inhom.derivatives) == 1
    assert inhom.derivatives[0].lorentz_index == mu
    assert inhom.fields[0].field.name == "alpha"

    # The second summand: replacement (alpha, A) with a structure constant
    # in the coupling.
    assert hom.derivatives == ()
    factor_names = [occ.field.name for occ in hom.fields]
    assert factor_names == ["alpha", "G"]
    coupling_str = str(hom.coupling)
    assert "f(" in coupling_str
    # And it carries the gauge coupling.
    assert "gS" in coupling_str


def test_pure_yang_mills_variation_is_well_formed():
    """Sanity check that applying ``gauge_variation`` to the **pure
    Yang-Mills Lagrangian** produces a finite, well-formed expression
    (no exceptions, no empty terms, alpha appears with a derivative).

    A full algebraic cancellation across the (bilinear + cubic + quartic)
    decomposition of ``F^2`` is *not* checked here for the reasons
    explained above; it is a known limitation of the minimal canonicaliser
    used in these unit tests.
    """

    g, Ag, SU3 = _su3_setup()
    mu, nu = S("mu"), S("nu")
    L = Model(
        gauge_groups=(SU3,),
        fields=(Ag,),
        lagrangian_decl=(
            -Expression.num(1) / Expression.num(4)
            * FieldStrength(SU3, mu, nu)
            * FieldStrength(SU3, mu, nu)
        ),
    ).lagrangian()

    delta = gauge_variation(group=SU3, parameter="alpha")
    dL = L.apply_operator(delta)

    # Every variation term must carry α somewhere.
    for term in dL.terms:
        names = [occ.field.name for occ in term.fields]
        assert "alpha" in names

    # The Symbolica export must include ``PartialD(alpha`` (the
    # inhomogeneous gauge-boson piece propagating through the F^2
    # derivatives).
    exported = dL.to_symbolica().expand()
    assert "PartialD(alpha" in str(exported)


def test_pure_yang_mills_variation_canonicalizes_to_zero_in_f_basis():
    """The fully expanded YM variation vanishes after the local tensor passes.

    The check intentionally keeps the color algebra in the explicit
    structure-constant basis so the Jacobi and antisymmetry reductions can act
    directly on ``f`` products.
    """

    g, Ag, SU3 = _su3_setup()
    mu, nu = S("mu"), S("nu")
    L = Model(
        gauge_groups=(SU3,),
        fields=(Ag,),
        lagrangian_decl=(
            -Expression.num(1) / Expression.num(4)
            * FieldStrength(SU3, mu, nu)
            * FieldStrength(SU3, mu, nu)
        ),
    ).lagrangian()

    delta = gauge_variation(group=SU3, parameter="alpha")
    exported = L.apply_operator(delta).to_symbolica().expand()
    lorentz, adjoint = _su3_pure_yang_mills_indices()

    canonical = canonize_full(
        exported,
        lorentz_indices=lorentz,
        adjoint_indices=adjoint,
        run_gamma=False,
        run_color=False,
    )
    assert canonical.to_canonical_string() == "0"


def test_pure_yang_mills_variation_canonicalizes_to_zero_with_inferred_indices():
    """YM zero check can infer Lorentz/adjoint index pools automatically."""

    g, Ag, SU3 = _su3_setup()
    mu, nu = S("mu"), S("nu")
    L = Model(
        gauge_groups=(SU3,),
        fields=(Ag,),
        lagrangian_decl=(
            -Expression.num(1) / Expression.num(4)
            * FieldStrength(SU3, mu, nu)
            * FieldStrength(SU3, mu, nu)
        ),
    ).lagrangian()

    delta = gauge_variation(group=SU3, parameter="alpha")
    exported = L.apply_operator(delta).to_symbolica().expand()
    canonical = canonize_full(
        exported,
        run_gamma=False,
        run_color=False,
        infer_indices=True,
        field_heads=(Ag,),
    )
    assert canonical.to_canonical_string() == "0"


def test_mixed_field_strength_bilinear_monomial_compiles_and_varies_to_zero():
    """A higher field-strength operator can mix multiple gauge symmetries.

    This exercises the declarative path

    ``kappa * (G^a_{mu nu} G^{a mu nu}) * (W^i_{rho sigma} W^{i rho sigma})``

    on top of the ordinary SU(3) x SU(2) x U(1) kinetic stack. The new
    monomial route should compile, and the infinitesimal SU(3) / SU(2)
    variations should still vanish after the local tensor passes.
    """

    _g3, Gg, SU3 = _su3_setup()
    _g2, Wg, SU2 = _su2_setup()
    B = Field("B", spin=1, indices=(LORENTZ_INDEX,), self_conjugate=True)
    U1 = GaugeGroup(
        name="U1Y",
        abelian=True,
        coupling=S("g1"),
        gauge_boson=B,
        charge="Y",
    )

    mu3, nu3 = S("mu3"), S("nu3")
    mu2, nu2 = S("mu2"), S("nu2")
    mu1, nu1 = S("mu1"), S("nu1")
    model = Model(
        gauge_groups=(SU3, SU2, U1),
        fields=(Gg, Wg, B),
        lagrangian_decl=(
            -(Expression.num(1) / Expression.num(4))
            * FieldStrength(SU3, mu3, nu3)
            * FieldStrength(SU3, mu3, nu3)
            - (Expression.num(1) / Expression.num(4))
            * FieldStrength(SU2, mu2, nu2)
            * FieldStrength(SU2, mu2, nu2)
            - (Expression.num(1) / Expression.num(4))
            * FieldStrength(U1, mu1, nu1)
            * FieldStrength(U1, mu1, nu1)
            + S("kappa")
            * FieldStrength(SU3, mu3, nu3)
            * FieldStrength(SU3, mu3, nu3)
            * FieldStrength(SU2, mu2, nu2)
            * FieldStrength(SU2, mu2, nu2)
        ),
    )

    compiled = model.lagrangian()
    assert compiled.terms

    for gauge_group in (SU3, SU2):
        delta = gauge_variation(group=gauge_group, parameter="alpha")
        exported = compiled.apply_operator(delta).to_symbolica().expand()
        canonical = canonize_full(
            exported,
            run_gamma=False,
            run_color=False,
            infer_indices=True,
            field_heads=(gauge_group.gauge_boson,),
        )
        assert canonical.to_canonical_string() == "0"
